apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
        - image: docker.io/pashacodefresh/pet-store:5da55d6583ed30df8317b4bd73010c7eafa5ef6a
          name: pet-store
          ports:
            - containerPort: 3001
