apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-store
  labels:
     app: 'cat-store'
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: cat-store
  template:
    metadata:
      labels:
        app: cat-store
    spec:
      containers:
        - image: docker.io/library/nginx:1.11
          name: cat-store
          ports:
            - containerPort: 3001
