apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-store
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: cat-store
  template:
    metadata:
      labels:
        app: cat-store
    spec:
      containers:
        - image: docker.io/pashacodefresh/pet-store:b9832aca87d611948ddb5348be40458da85f103a
          name: cat-store
          ports:
            - containerPort: 3001
