apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-store
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: cat-store
  template:
    metadata:
      labels:
        app: cat-store
    spec:
      containers:
        - image: docker.io/pashacodefresh/pet-store:97c8464d9897d75ae37e26715196237fea236a3f
          name: cat-store
          ports:
            - containerPort: 3001
